#!/usr/bin/env ruby

APPLICATION_NAME = 'qa_app'
RAILS_ROOT       = File.expand_path(File.join(File.dirname(__FILE__), '..'))

require 'rubygems'

def terminals
  rails_start       = "rails s"
  rails_console     = "rails c"

  [{
    'label'      => "[server]",
    'command'    => "cd #{RAILS_ROOT} && #{rails_start}",
  },{
    'label'      => "[console]",
    'command'    => "cd #{RAILS_ROOT} && #{rails_console}",
  },{
    'label'      => "[terminal]",
    'command'    => "cd #{RAILS_ROOT}",
  }].map { |hash| 
    hash['text']       = 'green'
    hash['background'] = [0, 0, 0]
    hash
  }
end

